#  environment document

name: covbatant1
channels:
  - conda-forge
  
dependencies:
  - python=3.7
  - jupyterlab
  - matplotlib=3.4
  - seaborn
  - pip 

  - pip:

    - neuroCombat
    - numpy==1.16.5
    - pandas==1.0.3

    # - git+https://github.com/andy1764/CovBat_Harmonization.git@main
    # - @ git+https://github.com/andy1764/CovBat_Harmonization.git@main
  



