#  neurocombat environment document

name: neuron
channels:
  - conda-forge
  
dependencies:
  - python=3.7
  # - numpy=1.16.5
  # - pandas=1.0.3
  - jupyterlab
  - matplotlib
  - pip 

  - pip:

    - neuroCombat
    - numpy==1.16.5
    - pandas==1.0.3
  
