#  environment document for combat-GAM neuroHarmonize package runnign
# note you should be using a python like 3.10 or 3.11
name: neurogamy
channels:
  - conda-forge
  
dependencies:

  - pandas
  - numpy
  - statsmodels
  - nibabel
  - jupyterlab

  - pip:

    - neuroHarmonize