#  neurocombat environment document

name: neuron_goal
channels:
  - conda-forge
  
dependencies:
  - python=3.7
  - jupyterlab
  - matplotlib=3.4
  - seaborn
  - scikit-learn
  - pip 

  - pip:

    - neuroCombat
    - numpy==1.16.5
    - pandas==1.0.3
  



