#  neurocombat environment document

name: neurocombaty
channels:
  - conda-forge
  
dependencies:
  - python=3.7
  #- neuroCombat
  - numpy=1.16.5
  - pandas=1.0.3
  - jupyterlab
  - matplotlib

  



