#  environment document

name: opncombat
channels:
  - conda-forge
  
dependencies:
  - pip:


    - pandas==1.5.2
    - neuroCombat==0.2.12
    - openpyxl
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - seaborn
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - numpy==1.24.2
    - jupyter
    - jupyterlab


