#  neurocombat environment document for further experiments (moore experiments)

name: more_neuron
channels:
  - conda-forge
  
dependencies:
  - python=3.7
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - pip 

  - pip:

    - neuroCombat
    - numpy==1.16.5
    - pandas==1.0.3
  
